### ISSUE TITLE
Bot does not add doi_brokendate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ms609/citation-bot#94] opened 2015-06-06 09:56 UTC
```
This change might have been a feature.  But I noticed that the doi_brokendate 
tag is not added for inactive DOI's anymore.

Useful to have those on this page:
http://en.wikipedia.org/wiki/Category:Pages_with_inactive_DOIs
so that they can be fixed (if wrong), or reported if right, or removed if not 
real (the AMA has many internal only ones that people try to use).



```

Original issue reported on code.google.com by `kurt.gla...@pnnl.gov` on 24 Oct 2011 at 6:32

**Comment by josve05a** [comment] 2017-01-09 12:35
Dupe of #73.

**Closed** 2017-09-05 05:27 UTC
Labels: auto-migrated, Priority-Low, Type-Defect
